Repository basetool-io/basetool, pull requests merged in 2021-11, with the labels that each got.

#180 chore: add funding and license
  .github/FUNDING.yml
  LICENSE.MD
Labels: chore

#181 fix: select all checkbox is ugly
  features/tables/components/TheTable.tsx
Labels: fix

#174 [BST-187] chore: dockerize app
  .dockerignore
  .env.sample
  Dockerfile
  components/Layout.tsx
  components/ProductionScripts.tsx
  deploy/docker/.env.sample
  deploy/docker/docker-compose.yml
  lib/gtag.ts
  lib/services.ts
  lib/track.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/api/auth/register.ts
  yarn.lock
Labels: chore, draft

#182 [BST-186] fix: records are not fetched on view change with same table
  features/records/api-slice.ts
  features/tables/components/RecordsTable.tsx
Labels: fix

#183 [BST-182] fix: time is not saved in UTC tz
  plugins/fields/DateTime/Edit.tsx
Labels: feature

#186 chore: update favicons and meta
  components/HeadSection.tsx
  lib/siteMeta.ts
  public/favicons/android-chrome-192x192.png
  public/favicons/android-chrome-512x512.png
  public/favicons/apple-touch-icon.png
  public/favicons/browserconfig.xml
  public/favicons/favicon-16x16.png
  public/favicons/favicon-32x32.png
  public/favicons/favicon.ico
  public/favicons/mstile-150x150.png
  public/favicons/safari-pinned-tab.svg
  public/img/cover.jpg
Labels: chore

#188 refactor: add basetool colors
  components/Layout.tsx
  components/PublicLayout.tsx
  components/Sidebar.tsx
  components/SidebarItem.tsx
  features/tables/components/TheTable.tsx
  lib/chakra.ts
  lib/globals.css
  tailwind.config.js
Labels: refactor

#187 fix: datasources sidebar kept last selected datasource when navigating to home
  hooks/index.ts
Labels: fix

#190 fix: intercom not visible
  lib/services.ts
  pages/api/auth/[...nextauth].ts
Labels: fix

#192 fix: boolean field misaligned
  plugins/fields/Boolean/Index.tsx
Labels: fix

#193 [BST-192] fix: filter for ProgressBar field is string instead of int
  components/ColumnListItem.tsx
  features/fields/factory.ts
  features/tables/components/ConditionComponent.tsx
  features/tables/index.ts
Labels: fix

#194 improvement: add image to login/register
  pages/auth/login.tsx
  pages/auth/register.tsx
  public/img/logo_text_black.png
Labels: feature

#195 fix: remove rogue semicolon that adds scrollbars
  pages/_app.tsx
Labels: fix

#196 [BST-135] fix: count fails when there's not id field
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
Labels: fix

#197 chore: capture user info on crash
  features/api/middleware.ts
Labels: chore

#199 [BST-198] fix: tables without id have item controls and create visible
  features/records/components/RecordsIndex.tsx
  features/tables/components/MobileRow.tsx
  features/tables/components/TheTable.tsx
Labels: fix

#200 [BST-200] chore: add docker start script
  .dockerignore
  package.json
  scripts/docker-start.mjs
Labels: chore

#201 fix: redirect login register
  next.config.js
Labels: fix

#204 Chore/use ga to update docker image
  .github/workflows/docker-publish.yml
  Dockerfile
Labels: chore

#206 [BST-201] feature: custom cell background
  features/code/evaluator.ts
  features/fields/components/BackgroundColorOption.tsx
  features/fields/components/FieldWrapper/IndexFieldWrapper.tsx
  features/fields/index.ts
  features/fields/types.d.ts
  features/tables/components/OptionsWrapper.tsx
  features/tables/components/TheTable.tsx
  lib/colors.js
  pages/data-sources/[dataSourceId]/edit/tables/[tableName]/columns.tsx
  pages/data-sources/[dataSourceId]/edit/tables/[tableName]/columns/[columnName].tsx
  styles/Home.module.css
  tailwind.config.js
  tsconfig.json
Labels: feature

#207 chore: remove redirects
  next.config.js
Labels: chore

#211 refactor: fetch the views in one query
  pages/api/views/index.ts
Labels: refactor

#210 refactor: remove columns order from backend
  features/data-sources/components/TableColumnsEditLayout.tsx
  features/records/api-slice.ts
  features/records/components/EditRecord.tsx
  features/records/components/ShowRecord.tsx
  features/records/index.ts
  features/tables/components/TheTable.tsx
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/columns.ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/[recordId].ts
  pages/api/records.ts
  pages/api/views/index.ts
Labels: refactor

#214 fix: get records query was being made twice
  features/tables/components/RecordsTable.tsx
Labels: fix

#215 add the create route back
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records.ts
  pages/api/records.ts
Labels: fix

#208 [BST-204] feature: store activity
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records.ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/[recordId].ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/bulk.ts
  prisma/migrations/20211105155559_add_activities/migration.sql
  prisma/migrations/20211108135526_add_action_to_activity/migration.sql
  prisma/schema.prisma
Labels: feature

#218 [BST-220] fix: datetime fields are sending updates on record update even when not needed
  plugins/fields/DateTime/Edit.tsx
Labels: fix

#217 [BST-197] feature: capture user timezone on login/register
  features/api/ApiService.ts
  features/auth/index.ts
  features/auth/signupSchema.ts
  pages/api/auth/[...nextauth].ts
  pages/api/auth/register.ts
  pages/auth/login.tsx
  pages/auth/register.tsx
  prisma/migrations/20211110111825_add_last_known_timezone_to_users/migration.sql
  prisma/schema.prisma
Labels: feature

#222 refactor: cast db credentials port as integer
  pages/api/data-sources/check-connection.ts
Labels: refactor

#223 fix: document not defined on build
  hooks/index.ts
Labels: fix

#224 refactor: useDatasourceContext hook
  features/app/state-slice.ts
  hooks/index.ts
Labels: refactor

#225 refactor: catch evaluator errors
  features/code/evaluator.ts
Labels: refactor

#227 chore: add fullstory integration
  .env.sample
  components/ProductionScripts.tsx
  pages/_app.tsx
Labels: chore

#228 fix: document not defined
  plugins/fields/Json/Show.tsx
Labels: fix

#229 chore: minor visual tweaks
  components/Shimmer.tsx
  components/ShimmerOrCount.tsx
  components/Sidebar.tsx
  pages/data-sources/[dataSourceId].tsx
  pages/views/[viewId].tsx
Labels: chore

#230 [BST-231] refactor: dataSource edit and table options
  components/Sidebar.tsx
  features/data-sources/api-slice.ts
  features/data-sources/components/DataSourceEditName.tsx
  features/data-sources/components/DataSourceEditSidebar.tsx
  features/data-sources/components/DataSourcesEditLayout.tsx
  features/data-sources/index.ts
  features/roles/AccessControlService.ts
  features/tables/api-slice.ts
  pages/api/data-sources/[dataSourceId].ts
  pages/api/data-sources/[dataSourceId]/tables.ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName].ts
  pages/data-sources/[dataSourceId]/edit/tables/[tableName].tsx
  pages/views/new.tsx
  plugins/data-sources/abstract-sql-query-service/types.d.ts
Labels: refactor

#226 refactor: persistent sql connections
  .env.sample
  .env.test.sample
  .github/workflows/docker-publish.yml
  .github/workflows/refresh-proxy.yml
  Dockerfile
  features/activity/components/ActivityItem.tsx
  features/api/middleware.ts
  features/api/urls.ts
  features/data-sources/components/NewDataSourceForm.tsx
  features/fields/components/FieldWrapper/ShowFieldWrapper.tsx
  features/fields/getColumns.ts
  features/records/api-slice.ts
  lib/constants.ts
  next.config.js
  pages/api/auth/[...nextauth].ts
  pages/api/data-sources/[dataSourceId]/query.ts
  pages/api/data-sources/[dataSourceId]/tables.ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records.ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/[recordId].ts
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/bulk.ts
  pages/api/hello.ts
  pages/api/records.ts
  pages/organizations/[organizationSlug]/activity.tsx
  plugins/data-sources/QueryServiceWrapper.ts
  plugins/data-sources/abstract-sql-query-service/index.ts
  plugins/data-sources/catalog.ts
  plugins/data-sources/getQueryService.ts
  plugins/data-sources/google-sheets/index.ts
  plugins/data-sources/serverHelpers.ts
  plugins/data-sources/types.d.ts
Labels: refactor

#236 refactor: add redis option for runInProxy
  .github/workflows/docker-publish.yml
  features/cache/index.ts
  features/options/index.ts
  lib/constants.ts
  plugins/data-sources/serverHelpers.ts
Labels: refactor

#203 [BST-195] feature: add mssql integration
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
  plugins/data-sources/index.ts
  plugins/data-sources/mssql/QueryService.ts
Labels: feature

#238 chore: use node 14 in docker
  Dockerfile
Labels: chore

#241 [BST-235] fix: wrong api path for recordId
  features/records/api-slice.ts
  pages/api/records/[recordId].ts
Labels: fix

#248 fix;l middleware memory leak
  features/api/middleware.ts
Labels: fix

#246 [BST-237] fix: itemControls and checkbox appear when there is no record id
  features/tables/components/BulkDeleteButton.tsx
  features/tables/components/CheckboxColumnCell.tsx
  features/tables/components/ItemControlsCell.tsx
  features/tables/components/RecordsTable.tsx
Labels: fix

#243 chore: upgrade next and better sentry tags
  features/api/middleware.ts
  package.json
  plugins/data-sources/serverHelpers.ts
  yarn.lock
Labels: chore

#235 [BST-215] feature: initial scan metadata
  pages/api/data-sources/[dataSourceId].ts
  pages/api/data-sources/index.ts
  plugins/data-sources/abstract-sql-query-service/doInitialScan.ts
  prisma/migrations/20211119102418_add_table_meta_data_to_datasource/migration.sql
  prisma/schema.prisma
Labels: feature

#249 [BST-243] fix: hide filter buttons on missing columns
  features/tables/components/FiltersPanel.tsx
  features/tables/components/GroupFiltersPanel.tsx
Labels: fix

#247 [BST-244] fix: make link clickable
  pages/index.tsx
Labels: fix

#245 refactor: cycle connections
  .env.sample
  lib/constants.ts
  pages/api/data-sources/[dataSourceId]/query.ts
  plugins/data-sources/ConnectionPooler.ts
  plugins/data-sources/QueryServiceWrapper.ts
  plugins/data-sources/catalog.ts
  plugins/data-sources/serverHelpers.ts
  plugins/data-sources/types.d.ts
Labels: refactor

#252 [BST-234] fix: association wrongly sends view ID
  features/records/index.ts
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
  plugins/fields/Association/Index.tsx
Labels: fix

#255 chore: pm2 connection count
  package.json
  plugins/data-sources/ConnectionPooler.ts
  yarn.lock
Labels: chore

#254 [BST-245] fix: failed request on load
  pages/views/new.tsx
Labels: refactor

#256 [BST-218] chore: disable analytics for checkly
  components/AnalyticsScripts.tsx
  components/ProductionScripts.tsx
  pages/_app.tsx
Labels: chore

#258 [BST-75] fix: wrong SQLError capture
  features/api/middleware.ts
Labels: fix

#262 chore: add more data sources to create new view
  plugins/data-sources/index.ts
  public/img/logos/intercom.png
  public/img/logos/redis.png
  public/img/logos/salesforce.png
  public/img/logos/shopify.png
  public/img/logos/zendesk.png
Labels: chore

#259 [BST-106] feature: stripe integration
  components/PageWrapper.tsx
  components/Sidebar.tsx
  features/data-sources/hooks.ts
  features/records/api-slice.ts
  features/records/components/EditRecord.tsx
  features/records/components/RecordsIndexPage.tsx
  features/records/components/ShowRecord.tsx
  features/records/hooks.ts
  features/records/index.ts
  features/tables/components/CursorPagination.tsx
  features/tables/components/ItemControls.tsx
  features/tables/components/OffsetPagination.tsx
  package.json
  pages/api/data-sources/index.ts
  pages/api/records.ts
  pages/api/records/[recordId].ts
  pages/data-sources/[dataSourceId]/tables/[tableName].tsx
  pages/data-sources/new.tsx
  pages/data-sources/stripe/new.tsx
  pages/views/[viewId].tsx
  pages/views/[viewId]/edit.tsx
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
  plugins/data-sources/abstract-sql-query-service/index.ts
  plugins/data-sources/getSchema.ts
  plugins/data-sources/google-sheets/QueryService.ts
  plugins/data-sources/google-sheets/index.ts
  plugins/data-sources/index.ts
  plugins/data-sources/serverHelpers.ts
  plugins/data-sources/stripe/QueryService.ts
  plugins/data-sources/stripe/index.ts
  plugins/data-sources/stripe/schema.ts
  plugins/data-sources/types.d.ts
  yarn.lock
Labels: feature

#261 [BST-247] feature: move associations data retrieval on be
  features/fields/index.ts
  features/fields/types.d.ts
  features/records/components/EditRecord.tsx
  features/records/components/Form.tsx
  features/records/components/NewRecord.tsx
  features/records/components/ShowRecord.tsx
  features/records/hooks.ts
  features/records/index.ts
  features/tables/components/RecordsTable.tsx
  features/views/components/ViewEditOrder.tsx
  pages/api/records.ts
  pages/api/records/[recordId].ts
  plugins/fields/Association/Edit.tsx
  plugins/fields/Association/Index.tsx
  plugins/fields/Association/Show.tsx
  plugins/fields/Association/helpers.ts
Labels: feature

#263 refactor: userViewResponse hook
  features/data-sources/hooks.ts
  features/records/components/RecordsIndexPage.tsx
  features/records/components/ShowRecord.tsx
  features/views/components/ViewEditDataSourceInfo.tsx
  features/views/components/ViewEditFilters.tsx
  features/views/components/ViewEditName.tsx
  features/views/components/ViewEditVisibility.tsx
  features/views/hooks.ts
  hooks/index.ts
  pages/views/[viewId].tsx
  pages/views/[viewId]/edit.tsx
Labels: refactor

#264 refactor: use ds response
  components/GoogleSheetsSetup.tsx
  features/data-sources/components/DataSourceEditName.tsx
  features/data-sources/components/DataSourcesEditLayout.tsx
  features/data-sources/hooks.ts
  features/records/components/EditRecord.tsx
  features/records/components/RecordsIndexPage.tsx
  features/records/components/ShowRecord.tsx
  features/tables/components/ItemControls.tsx
  features/views/components/ViewEditDataSourceInfo.tsx
  pages/data-sources/[dataSourceId].tsx
  pages/data-sources/[dataSourceId]/tables/[tableName].tsx
  pages/views/[viewId].tsx
  pages/views/[viewId]/edit.tsx
Labels: refactor

#265 refactor: useACLHelpers hook
  components/Sidebar.tsx
  features/authorization/hooks.ts
  features/records/components/EditRecord.tsx
  features/records/components/RecordsIndexPage.tsx
  features/records/components/ShowRecord.tsx
  features/tables/components/ItemControls.tsx
  features/views/components/ViewEditDataSourceInfo.tsx
  hooks/index.ts
Labels: refactor

#266 refactor: always show DS sidebar
  components/DataSourcesSidebar.tsx
Labels: refactor

#268 [BST-248] fix: bulk delete disabled
  features/tables/components/BulkDeleteButton.tsx
Labels: fix

#269 [BST-254] fix: virtual fields creation broken
  pages/api/views/[viewId]/columns.ts
Labels: fix

#276 fix: broken docker build process
  .github/workflows/docker-publish.yml
  Dockerfile
Labels: fix

#279 refactor: env variables for docker
  .env.sample
  components/AnalyticsScripts.tsx
  deploy/docker/.env.sample
  deploy/docker/docker-compose.yml
Labels: refactor

#280 chore: add sharp
  package.json
  yarn.lock
Labels: chore

#281 chore: minor refactor to dummy data sources
  components/PageWrapper.tsx
  features/data-sources/components/DummyDataSources.tsx
  pages/index.tsx
  pages/profile.tsx
  public/img/logos/stripe.png
Labels: chore

#282 chore: auto-deploy on VPS
  .github/workflows/refresh-proxy.yml
  .github/workflows/trigger-deploy.yml
Labels: chore

#288 fix: docker-compose image broken
  deploy/docker/docker-compose.yml
Labels: fix
