Repository basetool-io/basetool, pull requests merged in 2021-12, with the labels that each got.

#289 fix: azure mssql 'encrypt' option
  plugins/data-sources/abstract-sql-query-service/getKnexClient.ts
  plugins/data-sources/mssql/QueryService.ts
Labels: fix

#292 [BST-265] fix: missing found foreign record crashes records api call
  features/data-sources/components/DataSourcesBlock.tsx
  features/organizations/components/OrganizationsBlock.tsx
  features/records/index.ts
  pages/data-sources/[dataSourceId].tsx
  plugins/fields/Association/helpers.ts
Labels: fix

#293 fix: add filters
  pages/views/[viewId].tsx
  pages/views/[viewId]/edit.tsx
Labels: fix

#271 [BST-249 BST-250 BST-251] feature: feedback
  components/DataSourcesSidebar.tsx
  components/FeedbackPanel.tsx
  components/FeedbackSidebarItem.tsx
  features/app/api-slice.ts
  features/data-sources/components/DataSourceTileCreate.tsx
  features/views/components/ViewEditFilters.tsx
  hooks/index.ts
  lib/store.ts
  pages/api/feedback.ts
  pages/data-sources/new.tsx
Labels: feature

#287 chore: test docker image after build
  .github/workflows/docker-publish.yml
  .github/workflows/docker-publish/docker-setup.mjs
  .github/workflows/docker-publish/test-image.mjs
Labels: fix

#296 [BST-268] fix: JSON field broken
  plugins/fields/Json/Edit.tsx
Labels: fix

#298 chore: update nextjs
  .github/workflows/docker-publish.yml
  .github/workflows/reviewdog.yml
  next-env.d.ts
  package.json
  yarn.lock
Labels: chore

#297 [BST-271] fix: pretty 404 error message on edit
  features/records/components/EditRecord.tsx
  features/records/components/NewRecord.tsx
Labels: fix

#306 fix: MSSQL pagination issue
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
  yarn.lock
Labels: fix

#313 chore: tool.new takes a user to the creation flow
  lib/constants.ts
  pages/auth/register.tsx
  pages/index.tsx
Labels: chore

#322 fix: sidebar overflow broken
  components/OrganizationSidebar.tsx
  components/PageWrapper.tsx
  components/Sidebar.tsx
Labels: fix

#323 fix: register fields get unfocused
  pages/api/auth/register.ts
  pages/auth/register.tsx
Labels: fix

#324 [BST-275] fix: before value undefined
  pages/api/data-sources/[dataSourceId]/tables/[tableName]/records/[recordId].ts
Labels: fix

#325 [BST-276] fix: columns visible after disconnection
  features/tables/components/RecordsTable.tsx
  features/views/components/FieldEditor.tsx
Labels: fix

#326 [BST-274] fix: hidden error messages
  features/records/components/Form.tsx
Labels: fix

#327 [BST-79] fix: no default order for records
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
Labels: fix

#336 [BST-281] fix: counting for * is a performance issue
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
Labels: fix

#337 [BST-278] fix: aborted queries
  plugins/data-sources/ConnectionPooler.ts
Labels: fix

#329 [BST-280] fix: deleting columns breaks view
  pages/api/views/[viewId]/columns/[columnName].ts
Labels: fix

#338 chore: edit page improvements
  features/fields/components/FieldWrapper/EditFieldWrapper.tsx
  plugins/fields/Association/Edit.tsx
  plugins/fields/DateTime/Edit.tsx
  plugins/fields/Id/Edit.tsx
  plugins/fields/Number/Edit.tsx
  plugins/fields/ProgressBar/Edit.tsx
  plugins/fields/Select/Edit.tsx
  plugins/fields/Text/Edit.tsx
  plugins/fields/Textarea/Edit.tsx
Labels: chore

#339 chore: tailwindcss 3 update
  components/Layout.tsx
  components/PageWrapper.tsx
  components/SidebarItem.tsx
  features/activity/components/ActivityItem.tsx
  features/data-sources/components/DataSourceTileCreate.tsx
  features/data-sources/components/OptionWrapper.tsx
  features/tables/components/RecordsTable.tsx
  features/views/components/OptionWrapper.tsx
  package.json
  postcss.config.js
  tailwind.config.js
  yarn.lock
Labels: chore

#340 refactor: drop-downs in has many
  features/fields/hooks.ts
  features/tables/components/RecordsTable.tsx
  features/tables/hooks.ts
  features/tables/types.d.ts
  features/views/components/GenericSelectOption.tsx
  plugins/fields/LinkTo/Inspector.tsx
Labels: refactor

#349 chore: segment server tracking
  .env.sample
  lib/services.ts
  lib/track.ts
Labels: chore

#342 fix: dashboards disabled
  components/Sidebar.tsx
  features/dashboards/components/DashboardPage.tsx
  features/dashboards/components/DashboardsSidebarSection.tsx
  features/dashboards/components/WidgetView.tsx
  prisma/migrations/20211210142704_add_dashboard_item/migration.sql
Labels: fix

#350 refactor: add prefix to link fields
  plugins/fields/Text/Index.tsx
  plugins/fields/Text/Inspector.tsx
  plugins/fields/Text/fieldOptions.ts
  plugins/fields/Text/types.d.ts
Labels: refactor

#351 feature: widget refresh
  components/DashedCreateBox.tsx
  components/PageWrapper.tsx
  components/Sidebar.tsx
  features/api/index.ts
  features/api/middlewares/HasAccessToDashboard.ts
  features/dashboards/api-slice.ts
  features/dashboards/components/DashboardEditWidgets.tsx
  features/dashboards/components/DashboardPage.tsx
  features/dashboards/components/DashboardsSidebarSection.tsx
  features/dashboards/components/GenericTextOption.tsx
  features/dashboards/components/Widget.tsx
  features/dashboards/components/WidgetEditor.tsx
  features/dashboards/components/WidgetView.tsx
  features/dashboards/hooks.ts
  features/dashboards/server-helpers.ts
  features/dashboards/types.d.ts
  features/views/components/ViewsSidebarSection.tsx
  lib/constants.ts
  lib/globals.css
  pages/api/dashboards/[dashboardId].ts
  pages/api/dashboards/[dashboardId]/widgets/values.ts
  pages/api/widgets/[widgetId].ts
  pages/api/widgets/[widgetId]/value.ts
  pages/api/widgets/index.ts
  pages/dashboards/[dashboardId].tsx
  pages/dashboards/[dashboardId]/edit.tsx
  plugins/data-sources/abstract-sql-query-service/index.ts
  plugins/data-sources/google-sheets/index.ts
  plugins/data-sources/stripe/index.ts
  plugins/data-sources/types.d.ts
Labels: feature

#354 feature: reorder widgets
  features/dashboards/api-slice.ts
  features/dashboards/components/DashboardEditWidgets.tsx
  features/dashboards/components/DashboardPage.tsx
  lib/ItemTypes.ts
  pages/api/dashboards/[dashboardId]/widgets/order.ts
  pages/api/views/[viewId]/columns/order.ts
  pages/api/widgets/index.ts
  plugins/data-sources/abstract-sql-query-service/AbstractQueryService.ts
Labels: feature

#355 feature: group data sources by organization
  components/PageWrapper.tsx
  features/data-sources/components/DataSourcesBlock.tsx
  features/organizations/components/OrganizationsBlock.tsx
  pages/profile.tsx
Labels: feature

#359 chore: sentry hotfix revert
  next.config.js
  package.json
  yarn.lock
Labels: chore
